import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="text-hitam" lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, height=20, initial-scale=1, maximum-scale=1, user-scalable=no"></meta>
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
